### ISSUE TITLE
Undefined symbol: sdot_

### ISSUE THREAD

**Issue by ananv21** [david-cortes/recometrics#5]
Due to installation issues with the later versions of recometrics, I'm currently using version 0.1.6.post3. However, after the most recent recometrics update, I'm now running into the following error when I import recometrics: **ImportError: /usr/local/lib/python3.10/dist-packages/recometrics/cpp_funs.cpython-310-x86_64-linux-gnu.so: undefined symbol: sdot_**

I thought this might be due to incompatibility issues with the latest Cython/scipy versions so I downgraded both libraries to earlier versions (0.29.32 and 1.9.3 respectively) but I still seem to be running into these issues. I wasn't having any issues prior to the Cython/recometrics updates and I'm still using version 0.1.6.post3 of recometrics and not a newer version, so I'm not sure why I'm running into this error now. 

For additional reference, I'm using v.1.23.4 of numpy and v.1.5.1 of pandas. Here is the full list of dependencies for my code.
[requirements.txt](https://github.com/david-cortes/recometrics/files/12147330/requirements.txt)

**Comment by david-cortes** [comment]
There were changes in cython, which is used also at build time. If for some reason you need an older version of this package (note that the only changes since `post3` have been installation fixes), then you'll also need an older version of cython when building (not just as a runtime dependency).

Nevertheless, the latest version of this package (`0.1.6.post8`) should now work correctly with the latest cython.

**Comment by ananv21** [comment]
@david-cortes  When I try installing version 0.1.6.post8 (or any version past 0.1.6.post3), I run into the following error:
**NameError: name 'is_windows' is not defined**

This is thrown by the setuptools package which is called during installation. Do you know why this might be happening?

**Comment by david-cortes** [comment]
Thanks for pointing this out. Should be fixed now:
```shell
pip install recometrics==0.1.6.post9
```

**Comment by ananv21** [comment]
> Thanks for pointing this out. Should be fixed now:
> 
> ```shell
> pip install recometrics==0.1.6.post9
> ```

Thank you!
